backend:
  image:
    repository: ghcr.io/lebrick07/lebrickbot-backend
    tag: main-5c4be95
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 8000

frontend:
  image:
    repository: ghcr.io/lebrick07/lebrickbot-frontend
    tag: main-5c4be95
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: traefik
  host: openbrick.local
  path: /
  pathType: Prefix

github:
  enabled: true

aws:
  roleArn: ""
