{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-api
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /api
{{- end }}
