# Development Environment
namespace: openluffy-dev

backend:
  image:
    repository: ghcr.io/lebrick07/openluffy-backend
    tag: dev-ee6c2f2 # backend
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 8000

frontend:
  image:
    repository: ghcr.io/lebrick07/openluffy-frontend
    tag: dev-ee6c2f2 # frontend
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: traefik
  host: dev.openluffy.local
  path: /
  pathType: Prefix

github:
  enabled: true

aws:
  roleArn: ""
