# Pre-Production Environment
namespace: openluffy-preprod

backend:
  image:
    repository: ghcr.io/lebrick07/openluffy-backend
    tag: dev-6fd73e1 # backend
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 8000

frontend:
  image:
    repository: ghcr.io/lebrick07/openluffy-frontend
    tag: dev-6fd73e1 # frontend
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: traefik
  host: preprod.openluffy.local
  path: /
  pathType: Prefix

github:
  enabled: true

aws:
  roleArn: ""
