# Production Environment
namespace: openluffy-prod

backend:
  image:
    repository: ghcr.io/lebrick07/openluffy-backend
    tag: main-480ae15 # backend
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 8000

frontend:
  image:
    repository: ghcr.io/lebrick07/openluffy-frontend
    tag: main-480ae15 # frontend
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: traefik
  host: openluffy.local
  path: /
  pathType: Prefix

github:
  enabled: true

aws:
  roleArn: ""
